### ISSUE TITLE
Upgrade to Helm v3

### ISSUE THREAD

**Issue by npmaile** [homedepot/spingo#107]
v2 is depricated.

**Comment by npmaile** [comment]
also have helm set itself up in it's own little script in hal-scripts

**Comment by billiford** [comment]
I'd be careful with this - the vault helm chart IIRC warns not to use helm v3.

**Comment by npmaile** [comment]
yes

**Comment by billiford** [comment]
@npmaile this is completed as of https://github.com/homedepot/spingo/pull/115. Please close if you agree.
