### ISSUE TITLE
create a github action that validates all files and folders are kebab-case

### ISSUE THREAD

**Issue by billiford** [homedepot/spingo#90]
All files and folders in `spingo` should follow a convention - it has been chosen to be `kebab-case`.

 A github action should be created that checked all files and folder names recursively, failing if any file or folder is not `kebab-case`.

**Comment by npmaile** [comment]
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢 
🍢

**Comment by devorbitus** [comment]
You did that after the merge because if you had done it before the merge it may have not been merged eh?
